keywords:
  - 'stellar'
  - 'filecoin'
  - 'polkadot'
  - 'pancakeSwap'
  - 'algorand'
  - 'near'
  - 'serum'
  - 'chainlink'
  - 'gnosis'
  - 'decred'
  - 'cardano'
  - 'maker'
  - 'avalanche'
min_faves: 100
min_retweet: 10
pages: 30
wait_time: 30
